name: CI

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Checkout Own Repo
      uses: actions/checkout@v4
      with:
        repository: LWJ-Nicholas/DevOps_Oct2023_TeamC_Assignment
    - name: Install Library Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: list the contents
      run: |
        ls

    - name: Start Flask server
      run: |
        python main.py &
          
    - name: test with pytest
      run: |
        python -m pytest --junitxml=test.xml

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master

    - name: Run Robot Framework tests
      env:
        SELENIUM_BROWSER: headlesschrome
      run: |
        robot .

    - name: Create Issue on Failed workflow
      if: ${{ failure() }}
      id: create_issue
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
          assignees: LWJ-Nicholas

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        junit_files: "report.xml"